# Generated by Django 5.1.2 on 2025-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryOfOrigin', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.CharField(max_length=50)),
                ('max_load', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
