# Generated by Django 5.1.2 on 2025-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_product3dmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
