# Generated by Django 5.1.2 on 2025-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_product_model_3d_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product3dmodel',
            name='model_file',
            field=models.FileField(upload_to='StoreProject/StoreApp/models3d/'),
        ),
    ]
