# Generated by Django 5.1.2 on 2025-04-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='imageName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
