# Generated by Django 5.1.2 on 2025-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_alter_product3dmodel_model_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_3d_url',
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='models3d/'),
        ),
    ]
