# Generated by Django 5.1.2 on 2025-04-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_category_alter_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
