# Generated by Django 5.1.2 on 2025-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
