# Generated by Django 5.1.2 on 2025-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0009_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MainImg',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
    ]
