# Generated by Django 5.1.2 on 2025-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0010_product_mainimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_load',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
