# Generated by Django 5.1.2 on 2025-05-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0012_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
