# Generated by Django 5.1.2 on 2025-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0014_alter_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='StoreApp_pr_subcate_ea77b0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='StoreApp_pr_price_8cbf7c_idx'),
        ),
    ]
