# Generated by Django 5.1.2 on 2025-05-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0016_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_load',
            new_name='maxLoad',
        ),
        migrations.AddField(
            model_name='product',
            name='theBestProduct',
            field=models.BooleanField(default=True),
        ),
    ]
