# Generated by Django 5.1.2 on 2025-05-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0017_rename_max_load_product_maxload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='theBestProduct',
        ),
    ]
