# Generated by Django 5.1.2 on 2025-05-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0019_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='MainImg',
            new_name='mainImg',
        ),
    ]
